eureka:
  administrator:
    name: admin
    password: Welcome$18
  client:
    serviceUrl:
      defaultZone: http://${eureka.administrator.name}:${eureka.administrator.password}@localhost:8761/eureka
logging:
  level:
    org:
      springframework:
        web: DEBUG
    root: DEBUG
security:
  oauth2:
    client:
      access-token-uri: http://localhost:88/auth/oauth/token
      user-authorization-uri: http://localhost:88/auth/oauth/authorize
    resource:
      user-info-uri: http://localhost:88/auth/user