eureka:
  administrator:
    name: ${EUREKA_USERNAME}
    password: ${EUREKA_PASSWORD}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE}
  instance:
    metadata-map:
      user.name: ${ACTUATOR_USERNAME}
      user.password: ${ACTUATOR_PASSWORD}
management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS
security:
  oauth2:
    client:
      access-token-uri: ${AUTHORIZATION_SERVER_URI}/oauth/token
      user-authorization-uri: ${AUTHORIZATION_SERVER_URI}/oauth/authorize
    resource:
      prefer-token-info: false
      user-info-uri: ${AUTHORIZATION_SERVER_URI}/user
spring:
  security:
    user:
      name: ${eureka.instance.metadata-map.user.name}
      password: ${eureka.instance.metadata-map.user.password}
      roles: ACTUATOR