server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      fail-fast: true
      label: master
      profile: prod
      server:
        bootstrap: true
        git:
          uri: GIT_CONFIG_REPOSITORY_URI
        native:
          search-locations: file:./central-config
        prefix: /config
